### ISSUE TITLE
OKD 설치

### ISSUE THREAD

**Issue by dongheemin** [dongheemin/OKD_TEST#2]
OKD 설치
 * 준비물 1 : OKD install, client 최신버전 다운로드([OKD](https://github.com/okd-project/okd/tags))
 * 준비물 2 : Redhat pull secret([redhat.com](https://console.redhat.com/openshift/install/pull-secret))

**Comment by dongheemin** [comment]
installer, oc 설치

1. /data에서 작업
```
cd /data
```
2. install 밑작업
```
wget {OKD install Download Path}
tar -xvf {OKD install Path}
mv openshift-install /usr/sbin/
```
3. oc 밑작업
```
wget {OKD Client Download Path}
tar -xvf {OKD client Path}
mv kubectl /usr/sbin/
mv oc /usr/sbin/
```

**Comment by dongheemin** [comment]
OKD 설치 시작
1. install-config.yaml 생성
`vi install-config.yaml`
```
apiVersion: v1
baseDomain:{domain 입력}
metadata:
  name: {name 입력}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0  
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3   
networking: # 인프라가 바뀌면 적절히 세팅해줘야함
  clusterNetwork: # 사설 IP 대역으로 잡아야 함 = 클라우드 내에서 통신을 하기위한 IP 대역, 사설 IP 사용 시 다른 서비스와 겹치면 안되기 때문
  - cidr: 10.128.0.0/14 # 10대역 반짤라서 후반부 사용
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16 #172대역 반짤라서 후반부 사용
  machineNetwork:
  - cidr: 192.168.126.0/24 # 192.168.대역 반짤라서 후반 사용
platform:
  none: {}
pullSecret: '{redhat pullsecret 입력}'
sshKey: '{sshkey 입력}'
```
2. install 폴더 생성
`mkdir /data/install`

3. 링크파일 생성(★X1000000)
`ln -s /data/install-config.yaml /data/install/install-config.yaml`
> 생성하는 이유
>> 아래 명령어를 실행하게 되면 파일을 **지워버림**, ignition 파일 오류 등으로 인해 재실행하게 되면 문제가 발생함
>> ![image](https://github.com/dongheemin/OKD_TEST/assets/43870121/374110b0-96be-4ae2-a6f3-bccabf25f453)
>> ![image](https://github.com/dongheemin/OKD_TEST/assets/43870121/8dd0a63e-f34e-42f4-b27b-a542204049ca)


4. manifest 파일 생성
`openshift-install create manifests --dir=./install`
5. ignition 파일 생성
`openshift-install create ignition-configs --dir=./install`
7. ignition 파일 pxe 서버로 이동
`scp /data/install/*.ign {pxe 서버 위치}` 
> pxe 서버 설정은 팀장님꺼 씀
8. VM 4개를 더 켬(Bootstrap 1개, MasterNode 3개)
`virt-install --connect qemu:///system --quiet --name {VM이름 중복 ㄴㄴ} --os-variant fedora-coreos-stable --memory memory=16384,maxmemory=16384 --check path_in_use=off --wait -1 --noautoconsole --disk path=/vm/{VM이름}.qcow2,device=disk,bus=virtio,readonly=off,shareable=off,discard=unmap,driver_name=qemu,driver_type=qcow2,size=100 --network bridge=bridge,mac={DHCP에서 설정한 MAC주소} ,model=virtio,link_state=up --pxe --vcpus vcpus=4,maxvcpus=4,sockets=4,cores=1,threads=1`
9. PXE 부트에서 하나는 Bootstrap 3개는 Master로 설치
10. Bootstrap Login 가능 상태가 되면 아래와 같이 로그인하고 명령어 입력
```
ssh core@{bootstrap IP}
journalctl -b -f -u release-image.service -u bootkube.service
```
11. bastion에서 아래 명령어 입력(10과 동시진행)
`openshift-install wait-for bootstrap-complete`

12. 기다리면 아래같은 내용이 뜸

![Image](https://github.com/dongheemin/OKD_TEST/assets/43870121/4ce03f45-64ac-4454-b761-894630a44dc1)

![Image](https://github.com/dongheemin/OKD_TEST/assets/43870121/5e416b8a-ccfe-4f3e-a6e8-860ba8b27e13)

![Image](https://github.com/dongheemin/OKD_TEST/assets/43870121/fe0aa6ad-cc19-4f47-b47b-0b5480eb54b3)

 * bootstrap이 할일 다했다는 뜻


13. bastion에서 아래 명령어 입력(12 이후)
`openshift-install wait-for install-complete`


![Image](https://github.com/dongheemin/OKD_TEST/assets/43870121/86d46aff-8b9f-4705-942c-feaa78ca9443)


14. bootstrap 이미지 끄기
```
^C
exit
```
15. 마스터 노드 상태 확인
```
export KUBECONFIG=/data/install/auth/kubeconfig
oc get node
```

![Image](https://github.com/dongheemin/OKD_TEST/assets/43870121/1a89082d-4c85-43a9-9c25-3d551b009949)


16.
